[package]
name = "toile-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
arc-swap = "1"
crossbeam-channel = "0.5"
toile-doc = { path = "../toile-doc" }
toile-geom = { path = "../toile-geom" }
toile-mesh = { path = "../toile-mesh" }
toile-sim = { path = "../toile-sim" }

[lints]
workspace = true
